import { Footer, Header } from "@/components/layouts";
import "./globals.css";
import { Mulish, } from "next/font/google";
import { Montserrat } from 'next/font/google';
import Script from "next/script";
export const metadata = {
  title: "Gỗ Đại Thành",
  description: "Generated by create next app",
};
const mulish = Mulish({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-mulish",
  weight: ["400", "500", "700"],
});
const monsterrat = Montserrat({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-monsterrat",
  weight: ["400", "500", "700"],
});
export default function RootLayout({ children }) {
  return (
    <html className={monsterrat.className} lang="en">
      <body className={`$antialiased text-atcDark`}>
        <Header />
        {children}
        <Footer />
        <Script id="scroll-animation" strategy="afterInteractive">
          {`
            const observerOptions = {
              root: null,
              rootMargin: "0px",
              threshold: 0.15,
            };

            const revealCallback = (entries) => {
              entries.forEach((entry) => {
                if (entry.isIntersecting) {
                  entry.target.classList.add("active");
                }
              });
            };

            const observer = new IntersectionObserver(revealCallback, observerOptions);

            const observeElements = () => {
              const revealElements = document.querySelectorAll(".reveal, .reveal-stagger");
              revealElements.forEach((el) => observer.observe(el));
            };

            observeElements();
            
            const mutationObserver = new MutationObserver(observeElements);
            mutationObserver.observe(document.body, { childList: true, subtree: true });
          `}
        </Script>
      </body>
    </html>
  );
}
